server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启注册中心动态创建路由的功能，利用微服务名进行路由（注意配置有顺序，这个要在routes之上）
      routes:
        - id: payment_routh # 路由id，没有固定规则但要唯一，建议配合服务名
#          uri: http://localhost:8001 # 匹配后提供服务的路由地址
          uri: lb://cloud-payment-service # 匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/** # 断言，路径相匹配的进行路由
        - id: payment_routh2
#          uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            - Path=/provider/loadBalance/**
#            - After=2020-03-28T18:59:02.715+08:00[Asia/Shanghai]
#            - Cookie=name, aa # curl http://localhost:9527/provider/loadBalance --cookie "name=aa"
#            - Header=X-Request-Id, \d+ # curl http://localhost:9527/provider/loadBalance -H "X-Request-Id:2233"
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka