server:
  port: 8080
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3305/zhaofang?serverTimezone=Hongkong&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
  output:
    ansi:
      enabled: always # 控制台彩色输出
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.kealliang.laboratory.entities